Prejoining Assignment/Product Management System/Product Management System/Controllers/Products_ListController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Product_Management_System;
using Product_Management_System.Models;

namespace Product_Management_System.Controllers
{
    [Authorize]
    public class Products_ListController : Controller
    {
        private ProductManagementEntities db = new ProductManagementEntities();

        // GET: Products_List
        public ActionResult Index()
        {
            return View(db.Products_List.ToList());
        }

        // GET: Products_List/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Products_List products_List = db.Products_List.Find(id);
            if (products_List == null)
            {
                return HttpNotFound();
            }
            return View(products_List);
        }

        // GET: Products_List/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Products_List/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Product_id,Name,Category,Quantity,Short_Description,Long_Description,Small_Image,Price")] Products_List products_List)
        {
            if (ModelState.IsValid)
            {
                db.Products_List.Add(products_List);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(products_List);
        }

        // GET: Products_List/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Products_List products_List = db.Products_List.Find(id);
            if (products_List == null)
            {
                return HttpNotFound();
            }
            return View(products_List);
        }

        // POST: Products_List/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Product_id,Name,Category,Quantity,Short_Description,Long_Description,Small_Image,Price")] Products_List products_List)
        {
            if (ModelState.IsValid)
            {
                db.Entry(products_List).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(products_List);
        }

        // GET: Products_List/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Products_List products_List = db.Products_List.Find(id);
            if (products_List == null)
            {
                return HttpNotFound();
            }
            return View(products_List);
        }

        // POST: Products_List/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Products_List products_List = db.Products_List.Find(id);
            db.Products_List.Remove(products_List);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Prejoining Assignment/Product Management System/Product Management System/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Product Management", "Index", "Products_List", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Products_List")</li>


                    @if (User.Identity.IsAuthenticated)
                    {
                        <li><a>Hello - @User.Identity.Name</a></li>
                        <li>@Html.ActionLink("Products List", "Index", "Products_List")</li>
                        <li>@Html.ActionLink("Add Products", "Create", "Products_List")</li>
                        <li>@Html.ActionLink("Logout", "Logout", "Account")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Login", "Login", "Account")</li>
                    }

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>